-- Enable pgvector extension
    CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE clubes (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
	"Country" VARCHAR(255) NOT NULL,
	"State" VARCHAR(255) NOT NULL,
    "Description" TEXT NOT NULL
);


-- Create embedding table for sobreclubes
CREATE TABLE sobreclubes (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
	"ClubeId" uuid REFERENCES clubes("Id"),
    "Name" VARCHAR(255) NOT NULL,
	"Country" VARCHAR(255) NOT NULL,
	"State" VARCHAR(255) NOT NULL,
    "Description" TEXT NOT NULL,
    "Embedding" vector(1024) NOT NULL -- Ollama (mxbai-embed-large:latest) embeddings have 1024 dimensions. change according your embedding model
);

CREATE INDEX idx_sobre_clubes_embedding 
ON sobreclubes 
USING hnsw ("Embedding" vector_l2_ops); 



INSERT INTO clubes ("Name", "Country", "State", "Description") VALUES
('Flamengo', 'Brazil', 'Rio de Janeiro', 'Flamengo is one of the most successful football clubs in Brazil, with a rich history of achievements. In recent years, Flamengo has dominated Brazilian football, winning multiple Campeonato Brasileiro Série A titles, including the 2019 and 2020 seasons. The club also secured the Copa Libertadores title in 2019, defeating River Plate in a dramatic final. Flamengo is known for its passionate fan base, the "Nação Rubro-Negra," and its iconic red and black colors. The team plays its home matches at the historic Maracanã Stadium, which has witnessed countless memorable moments in football history.'),
('Liverpool', 'England', 'Merseyside', 'Liverpool FC, founded in 1892, is one of the most iconic football clubs in the world. In recent years, the club has experienced a resurgence under manager Jürgen Klopp, winning the UEFA Champions League in 2019 and their first Premier League title in 30 years in the 2019-2020 season. Known for their attacking style of play and passionate fan base, the "Reds" play their home games at Anfield, where the famous "You’ll Never Walk Alone" anthem resonates. Liverpool continues to be a dominant force in both domestic and European competitions.'),
('Barcelona', 'Spain', 'Catalonia', 'FC Barcelona, commonly referred to as Barça, is one of the most successful and popular football clubs in the world. The club has a rich history of success, including recent triumphs in La Liga and the Copa del Rey. Despite facing challenges in recent years, Barcelona remains a powerhouse in European football, with a focus on developing young talent through their famed La Masia academy. The team plays its home matches at Camp Nou, one of the largest stadiums in the world, and is known for its attacking style of play and the motto "Més que un club" (More than a club).'),
('Paris Saint-Germain', 'France', 'Île-de-France', 'Paris Saint-Germain (PSG) has established itself as the dominant force in French football over the past decade. With a star-studded lineup featuring players like Kylian Mbappé and Neymar, PSG has won multiple Ligue 1 titles and domestic cups. The club reached the UEFA Champions League final in 2020, showcasing its growing stature in European football. PSG is known for its attacking flair, financial backing, and passionate fan base. The team plays its home matches at the Parc des Princes in Paris, a city synonymous with elegance and style.'),
('Boca Juniors', 'Argentina', 'Buenos Aires', 'Boca Juniors is one of the most successful and popular football clubs in Argentina and South America. Known for their fierce rivalry with River Plate, Boca has a storied history of success, including numerous Copa Libertadores titles. In recent years, the club has continued to compete at the highest level, winning domestic championships and maintaining its reputation as a breeding ground for top talent. Boca Juniors plays its home matches at La Bombonera, a stadium famous for its unique architecture and electric atmosphere.'),
('Juventus', 'Italy', 'Piedmont', 'Juventus, also known as "La Vecchia Signora" (The Old Lady), is one of the most successful football clubs in Italy and Europe. The club has dominated Serie A in recent years, winning nine consecutive league titles from 2012 to 2020. Juventus is known for its strong defensive play and iconic black-and-white striped jerseys. The team plays its home matches at the Allianz Stadium in Turin and continues to be a major contender in both domestic and European competitions.'),
('Atlético Mineiro', 'Brazil', 'Minas Gerais', 'Atlético Mineiro, also known as Galo, is one of Brazil’s most historic football clubs. In recent years, the club has achieved significant success, including winning the Campeonato Brasileiro Série A in 2021 after a 50-year drought. The team also secured the Copa do Brasil and the Supercopa do Brasil in the same season, marking a historic treble. Atlético Mineiro is known for its passionate fan base and plays its home matches at the Mineirão Stadium in Belo Horizonte.'),
('Chelsea', 'England', 'London', 'Chelsea FC, based in London, is one of the most successful football clubs in England and Europe. The club has enjoyed tremendous success in recent years, including winning the UEFA Champions League in 2021 under manager Thomas Tuchel. Chelsea is known for its strong squad depth, financial backing, and iconic blue kits. The team plays its home matches at Stamford Bridge, a stadium steeped in history and tradition.'),
('Real Madrid', 'Spain', 'Madrid', 'Real Madrid is widely regarded as the most successful football club in the world. The club has an unparalleled record in the UEFA Champions League, with 14 titles, including their most recent triumph in 2022. Known for their "Galácticos" era and star-studded lineups, Real Madrid continues to dominate both domestically and in Europe. The team plays its home matches at the Santiago Bernabéu Stadium, which is undergoing a state-of-the-art renovation.'),
('Olympique de Marseille', 'France', 'Provence-Alpes-Côte d’Azur', 'Olympique de Marseille, commonly referred to as OM, is one of the most historic football clubs in France. The club has a passionate fan base and a rich history, including winning the UEFA Champions League in 1993. In recent years, OM has been a consistent contender in Ligue 1 and European competitions. The team plays its home matches at the Stade Vélodrome, known for its electric atmosphere.'),
('River Plate', 'Argentina', 'Buenos Aires', 'River Plate is one of the most successful and popular football clubs in Argentina and South America. Known for their fierce rivalry with Boca Juniors, River Plate has a storied history of success, including multiple Copa Libertadores titles. In recent years, the club has continued to dominate domestically and internationally, showcasing its attacking style of play. River Plate plays its home matches at the Estadio Monumental, one of the largest stadiums in South America.'),
('AC Milan', 'Italy', 'Lombardy', 'AC Milan, one of the most iconic football clubs in Italy, has experienced a resurgence in recent years. The club won the Serie A title in the 2021-2022 season, ending an 11-year drought. Known for their rich history in European competitions, including seven UEFA Champions League titles, AC Milan continues to be a major force in Italian football. The team plays its home matches at the San Siro Stadium, which it shares with city rivals Inter Milan.'),
('Corinthians','Brazil','Sao Paulo', 'O Corinthians é um dos clubes mais populares do Brasil, fundado em 1910 e dono de uma história repleta de títulos importantes. Entre suas maiores conquistas estão a Libertadores da América de 2012, o Mundial de Clubes da FIFA de 2000 e 2012, além de vários Campeonatos Brasileiros, Copas do Brasil e inúmeros títulos estaduais pelo Paulistão. Suas cores tradicionais são preto e branco, que simbolizam simplicidade e força. O mascote oficial é o Mosqueteiro, escolhido por representar coragem e espírito de luta — características marcantes da identidade corinthiana. A torcida do Corinthians, conhecida como Fiel Torcida, é famosa por sua paixão incondicional e apoio fervoroso ao time, tanto em jogos no Brasil quanto em competições internacionais.'),
('Palmeiras','Brazil','Sao Paulo', 'O Palmeiras, fundado em 1914, é um dos clubes mais tradicionais e vitoriosos do futebol brasileiro. Com uma rica história de conquistas, o clube acumula títulos importantes como a Copa Libertadores da América, o Campeonato Brasileiro e a Copa do Brasil. O Palmeiras é conhecido por sua forte base de torcedores e por sua rivalidade histórica com outros grandes clubes paulistas, como o Corinthians e o São Paulo FC. As cores oficiais do Palmeiras são o verde e a branco, que representam a esperança e a paz. O mascote do clube é o Porco, símbolo de força e determinação, adotado pela torcida como um emblema de orgulho. A torcida do Palmeiras, conhecida como Palestra Itália, é reconhecida por sua paixão e lealdade ao clube, apoiando-o fervorosamente em todas as competições.'),
('São Paulo FC','Brazil','Sao Paulo', 'O São Paulo Futebol Clube, fundado em 1930, é um dos clubes mais prestigiados do futebol brasileiro e mundial. Com uma história repleta de conquistas, o São Paulo acumula títulos importantes como a Copa Libertadores da América, o Mundial de Clubes da FIFA e vários Campeonatos Brasileiros. O clube é conhecido por sua estrutura profissional e por revelar grandes talentos para o futebol nacional e internacional. As cores oficiais do São Paulo FC são o vermelho, branco e preto, que simbolizam a paixão, a paz e a força. O mascote do clube é o Soberano, representando a grandeza e a tradição do time. A torcida do São Paulo FC, conhecida como Tricolor Paulista, é famosa por sua dedicação e apoio incondicional ao clube em todas as competições.'),
('Santos FC','Brazil','Sao Paulo', 'O Santos Futebol Clube, fundado em 1912, é um dos clubes mais icônicos do futebol brasileiro, conhecido mundialmente por revelar talentos extraordinários como Pelé e Neymar. Com uma rica história de conquistas, o Santos acumula títulos importantes como a Copa Libertadores da América, o Mundial de Clubes da FIFA e vários Campeonatos Brasileiros. O clube é reconhecido por seu estilo de jogo ofensivo e pela formação de jogadores que se destacam no cenário internacional. As cores oficiais do Santos FC são o branco e o preto, que representam a pureza e a força. O mascote do clube é o Baleia, simbolizando a grandeza e a tradição do time. A torcida do Santos FC, conhecida como Santástica, é famosa por sua paixão e apoio fervoroso ao clube em todas as competições.');
