-- Enable pgvector extension
    CREATE EXTENSION IF NOT EXISTS vector;

-- Create embedding table for recomendation
CREATE TABLE product_recomendation (
   "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Category" VARCHAR(255) NOT NULL,
    "Price" DECIMAL(10,2) NOT NULL,
    "Description" TEXT NOT NULL,
    "Embedding" vector(768)  NULL, -- Gemini embeddings have 768 dimensions. change according your embedding model
    "EmbeddingLLM" vector(1024)  NULL -- Ollama (mxbai-embed-large:latest) embeddings have 1024 dimensions. change according your embedding model
);



CREATE INDEX idx_recomendation_embedding 
ON product_recomendation 
USING hnsw ("Embedding" vector_l2_ops); 


CREATE TABLE products (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(255) NOT NULL,
    "Category" VARCHAR(255) NOT NULL,
    "Price" DECIMAL(10,2) NOT NULL,
    "Description" TEXT NOT NULL
);


    INSERT INTO products ("Name", "Category","Price","Description") VALUES
        ('Running Shoes ABC', 'Footwear', 129.99, 'Experience comfort and performance with Running Shoes ABC, designed for athletes of all levels with breathable materials and superior cushioning.'),
    ('Smartphone XYZ', 'Electronics', 699.99, 'The Smartphone XYZ features a stunning display, powerful processor, and an advanced camera system to capture your best moments. This device is designed to keep you connected and productive throughout the day with its long-lasting battery and sleek design.'),
    ('Gaming Console Alpha', 'Games', 499.99, 'The Gaming Console Alpha delivers an immersive gaming experience with stunning graphics, fast load times, and a vast library of games. Enjoy multiplayer gaming and exclusive titles that redefine entertainment. Built for gamers of all levels.'),
    ('Smart Refrigerator', 'Home', 1199.99, 'The Smart Refrigerator keeps your food fresh and organized with advanced cooling technology and smart features. Monitor and control settings remotely, and enjoy a sleek design that complements any modern kitchen. Energy-efficient and reliable.'),
    ('Organic Snack Pack', 'Food', 19.99, 'The Organic Snack Pack offers a healthy and delicious assortment of snacks made from natural ingredients. Perfect for on-the-go lifestyles, these snacks are packed with flavor and nutrition. Enjoy guilt-free snacking anytime.'),
    ('Gaming Laptop Pro', 'PC', 1499.99, 'The Gaming Laptop Pro is designed for high-performance gaming and productivity. Featuring a powerful processor, advanced graphics, and a sleek design, this laptop is perfect for gamers and professionals alike. Stay ahead with cutting-edge technology.'),
    ('Home Security Camera', 'Security', 99.99, 'The Home Security Camera provides peace of mind with high-definition video, motion detection, and remote monitoring. Protect your home and loved ones with this easy-to-install and reliable security solution. Stay connected and secure.'),
    ('Wireless Headphones', 'Electronics', 199.99, 'Experience superior sound quality and comfort with Wireless Headphones. Enjoy long battery life, noise cancellation, and a sleek design. Perfect for music lovers and professionals who value high-quality audio.'),
    ('VR Headset', 'Games', 299.99, 'Immerse yourself in virtual worlds with the VR Headset. Enjoy stunning visuals, intuitive controls, and a comfortable fit. Perfect for gaming, entertainment, and exploring new dimensions of reality. Built for endless adventures.'),
    ('Smart Vacuum Cleaner', 'Home', 399.99, 'The Smart Vacuum Cleaner makes cleaning effortless with advanced navigation, powerful suction, and smart features. Control it remotely and enjoy a cleaner home with minimal effort. Perfect for busy households.'),
    ('Gourmet Coffee Beans', 'Food', 24.99, 'Indulge in the rich flavor of Gourmet Coffee Beans. Sourced from the finest plantations, these beans deliver a smooth and aromatic coffee experience. Perfect for coffee enthusiasts and connoisseurs.'),
    ('Desktop Workstation', 'PC', 999.99, 'The Desktop Workstation is built for productivity and performance. Featuring a powerful processor, ample storage, and a sleek design, this workstation is perfect for professionals and creatives. Stay ahead with reliable technology.'),
    ('Smart Door Lock', 'Security', 149.99, 'The Smart Door Lock enhances your home security with keyless entry, remote access, and advanced encryption. Protect your home and loved ones with this reliable and easy-to-install solution. Stay secure and connected.'),
    ('4K Smart TV', 'Electronics', 799.99, 'Enjoy stunning visuals and immersive sound with the 4K Smart TV. Featuring advanced technology, a sleek design, and smart features, this TV is perfect for entertainment enthusiasts. Experience the future of television.'),
    ('Gaming Keyboard', 'Games', 129.99, 'The Gaming Keyboard delivers precision and performance with customizable keys, RGB lighting, and a durable design. Perfect for gamers who demand the best. Enhance your gaming experience with this high-quality keyboard.'),
    ('Smart Thermostat', 'Home', 249.99, 'The Smart Thermostat helps you save energy and stay comfortable with advanced temperature control and remote access. Monitor and adjust settings from anywhere. Perfect for modern homes and eco-conscious users.'),
    ('Energy Bar Variety Pack', 'Food', 14.99, 'Stay energized with the Energy Bar Variety Pack. Packed with natural ingredients and delicious flavors, these bars are perfect for on-the-go lifestyles. Enjoy a healthy and convenient snack anytime.'),
    ('All-in-One PC', 'PC', 1299.99, 'The All-in-One PC combines sleek design with powerful performance. Featuring a large display, advanced technology, and a space-saving design, this PC is perfect for home and office use. Stay productive and stylish.'),
    ('Surveillance System', 'Security', 499.99, 'The Surveillance System provides comprehensive security with high-definition cameras, motion detection, and remote monitoring. Protect your property and loved ones with this reliable and easy-to-install solution.'),
    ('Bluetooth Speaker', 'Electronics', 99.99, 'Enjoy powerful sound and portability with the Bluetooth Speaker. Perfect for music lovers, this speaker delivers high-quality audio and a sleek design. Take your music anywhere and enjoy the ultimate listening experience.'),
    ('Gaming Mouse', 'Games', 79.99, 'The Gaming Mouse offers precision and performance with customizable buttons, RGB lighting, and a comfortable design. Perfect for gamers who demand the best. Enhance your gaming experience with this high-quality mouse.'),
    ('Smart Light Bulb', 'Home', 29.99, 'The Smart Light Bulb lets you control your lighting with ease. Adjust brightness, color, and schedules remotely. Perfect for modern homes and eco-conscious users. Enjoy convenience and energy savings.'),
    ('Gourmet Chocolate Box', 'Food', 34.99, 'Indulge in the rich flavors of the Gourmet Chocolate Box. Made from the finest ingredients, this box offers a variety of delicious chocolates. Perfect for gifting or treating yourself.'),
    ('High-Performance Desktop', 'PC', 1999.99, 'The High-Performance Desktop is designed for demanding tasks and gaming. Featuring advanced technology, ample storage, and a sleek design, this desktop is perfect for professionals and gamers alike.'),
    ('Smart Alarm System', 'Security', 299.99, 'The Smart Alarm System enhances your home security with advanced sensors, remote access, and reliable performance. Protect your home and loved ones with this easy-to-install solution. Stay secure and connected.'),
    ('Noise-Cancelling Earbuds', 'Electronics', 149.99, 'Experience superior sound quality and comfort with Noise-Cancelling Earbuds. Enjoy long battery life, noise cancellation, and a sleek design. Perfect for music lovers and professionals who value high-quality audio.'),
    ('Gaming Chair', 'Games', 249.99, 'The Gaming Chair offers comfort and support for long gaming sessions. Featuring ergonomic design, adjustable settings, and a sleek look, this chair is perfect for gamers who demand the best.'),
    ('Smart Air Purifier', 'Home', 299.99, 'The Smart Air Purifier improves your indoor air quality with advanced filtration and smart features. Monitor and control settings remotely. Perfect for modern homes and health-conscious users.'),
    ('Artisan Cheese Platter', 'Food', 49.99, 'The Artisan Cheese Platter offers a selection of premium cheeses crafted from the finest ingredients. Perfect for entertaining or enjoying a gourmet treat. Indulge in the rich flavors and textures.'),
    ('Portable Workstation', 'PC', 1799.99, 'The Portable Workstation is designed for professionals on the go. Featuring powerful performance, a sleek design, and advanced technology, this workstation is perfect for productivity and creativity.'),
    ('Smart Home Hub', 'Security', 199.99, 'The Smart Home Hub connects and controls your smart devices with ease. Enjoy seamless integration, remote access, and advanced features. Perfect for modern homes and tech enthusiasts.'),
    ('Wireless Charger', 'Electronics', 49.99, 'The Wireless Charger offers fast and convenient charging for your devices. Featuring a sleek design and reliable performance, this charger is perfect for home and office use. Stay powered up effortlessly.'),
    ('Gaming Monitor', 'Games', 399.99, 'The Gaming Monitor delivers stunning visuals and fast refresh rates for an immersive gaming experience. Perfect for gamers who demand the best. Enhance your setup with this high-quality monitor.'),
    ('Smart Coffee Maker', 'Home', 199.99, 'The Smart Coffee Maker brews the perfect cup of coffee with advanced features and remote control. Enjoy convenience and quality with this sleek and reliable coffee maker. Perfect for coffee lovers.'),
    ('Gourmet Snack Basket', 'Food', 59.99, 'The Gourmet Snack Basket offers a variety of delicious and premium snacks. Perfect for gifting or enjoying a gourmet treat. Indulge in the rich flavors and textures.'),
    ('Ultra-Slim Laptop', 'PC', 1299.99, 'The Ultra-Slim Laptop combines portability and performance with a sleek design and advanced technology. Perfect for professionals and students who value style and functionality. Stay productive on the go.'),
    ('Smart Security System', 'Security', 599.99, 'The Smart Security System provides comprehensive protection with advanced sensors, cameras, and remote access. Protect your home and loved ones with this reliable and easy-to-install solution.'),
    ('Portable Bluetooth Speaker', 'Electronics', 79.99, 'Enjoy powerful sound and portability with the Portable Bluetooth Speaker. Perfect for music lovers, this speaker delivers high-quality audio and a sleek design. Take your music anywhere and enjoy the ultimate listening experience.'),
    ('Gaming Headset', 'Games', 149.99, 'The Gaming Headset delivers immersive sound and comfort for long gaming sessions. Featuring advanced audio technology and a sleek design, this headset is perfect for gamers who demand the best.'),
    ('Smart Washing Machine', 'Home', 899.99, 'The Smart Washing Machine makes laundry effortless with advanced features and remote control. Enjoy convenience and quality with this sleek and reliable appliance. Perfect for modern homes.'),
    ('Gourmet Pasta Kit', 'Food', 39.99, 'The Gourmet Pasta Kit offers everything you need to create delicious and authentic pasta dishes. Perfect for home cooks and food enthusiasts. Indulge in the rich flavors and textures.'),
    ('High-Performance Laptop', 'PC', 1599.99, 'The High-Performance Laptop is designed for demanding tasks and gaming. Featuring advanced technology, ample storage, and a sleek design, this laptop is perfect for professionals and gamers alike.'),
    ('Smart Doorbell', 'Security', 199.99, 'The Smart Doorbell enhances your home security with video monitoring, motion detection, and remote access. Protect your home and loved ones with this reliable and easy-to-install solution. Stay secure and connected.');