-- Enable pgvector extension
    CREATE EXTENSION IF NOT EXISTS vector;


CREATE TABLE mydocuments (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    "Title" VARCHAR(255) NOT NULL,
    "DocText" TEXT NOT NULL
);


-- Create embedding table for sobreclubes
CREATE TABLE documents_recomendation (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(255) NOT NULL,
    "DocText" TEXT NOT NULL,
    "DocumentId" uuid REFERENCES mydocuments("Id"),
    "Embedding" vector(768) NOT NULL -- Gemini embeddings have 768 dimensions. change according your embedding model
);

CREATE INDEX idx_documents_recomendation_embedding 
ON documents_recomendation 
USING hnsw ("Embedding" vector_l2_ops); 

